version: "3.8"

networks:
  wordle-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

services:
  frontend:
    image: nginx:alpine
    container_name: wordle-frontend
    ports:
      - "${FRONTEND_HOST:-127.0.10.11}:${FRONTEND_PORT:-8080}:80"
    volumes:
      - ./test-content/frontend:/usr/share/nginx/html:ro
    networks:
      - wordle-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    image: httpd:alpine
    container_name: wordle-api-gateway
    ports:
      - "${API_GATEWAY_HOST:-127.0.10.11}:${API_GATEWAY_PORT:-8082}:80"
    volumes:
      - ./test-content/api:/usr/local/apache2/htdocs:ro
    networks:
      - wordle-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: wordle-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - wordle-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wordle-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - wordle-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--no-auth-warning",
          "-a",
          "${REDIS_PASSWORD}",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
